<?php
return [
    'number_limit' => 4,
    'default' => 0,
    'user' => 1,
    'admin' => 2,
    'mod' => 3,
    'number_paginate' => 1,
    'number_lessonPaginate' => 1,
    'number_topicPaginate' => 1,
    'number_userPaginate' => 2,
    'number_whereRoleID' => 1,
    'statusUser' => 1,
    'id_genderMale' => 0,
    'id_genderFemale' => 1,
    'name_genderMale' => 'Male',
    'name_genderFemale' => 'Female',
    'unknown_user_img' => 'unknown-user.jpg',
    'folder_user_img' => 'images/users',
    'status_userActive1' => 1,
    'status_userActive0' => 0,
];
