<?php
return [
    'number_limitLessonToday' => 4,
    'number_limit' => 6,
    'number_limitTopic' => 4,
    'default' => 0,
    'user' => 3,
    'admin' => 1,
    'mod' => 2,
    'number_paginate' => 3,
    'number_lessonPaginate' => 3,
    'number_topicPaginate' => 3,
    'number_userPaginate' => 2,
    'number_whereRoleID' => 1,
    'statusUser' => 1,
    'id_genderMale' => 0,
    'id_genderFemale' => 1,
    'name_genderMale' => 'Male',
    'name_genderFemale' => 'Female',
    'unknown_user_img' => 'unknown-user.jpg',
    'folder_user_img' => 'images/users',
    'status_userActive1' => 1,
    'status_userActive0' => 0,
    'number_wordmanagerpaginater' => 10,
    'word_file_path' => 'images/words/',
    'word_file_audio_path' => 'audio',
    'file_save_lesson' => 'images/lessons/',
    'number_lessonmanagerpaginater' => 10,
    'folder_topic_img' => 'images/topics',
    'passPercent' => 70,
    'numberDefault0' => 0,
    'numberDefault1' => 1,
    'numberFormat' => 2,
    'wordsPaginate' => 50,
    'savedDefault' => 0,
    'check_exist_test' => 0,
];
